

export const SEND_PLACE_REQUEST = "SEND_PLACE_REQUEST"
export const SUCCESS_PLACE_REQUEST = "SUCCESS_PLACE_REQUEST"
export const FAILD_PLACE_REQUEST = "FAILD_PLACE_REQUEST"
export const SEND_ON_PROGRESS = "SEND_ON_PROGRESS"